DROP TABLE IF EXISTS request_info;

CREATE TABLE request_info (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    username TEXT UNIQUE NOT NULL,
    device TEXT UNIQUE NOT NULL,
    cookie TEXT UNIQUE NOT NULL,
    x_tt_token TEXT UNIQUE NOT NULL
);